In [25]:
import pandas as pd
import sklearn as sk
import numpy as np
import seaborn as sn
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import cross_val_score

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from xgboost import XGBClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis
from sklearn.linear_model import LogisticRegression
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.cluster import KMeans
from sklearn.ensemble import StackingClassifier
from sklearn.svm import LinearSVC
from sklearn.ensemble import ExtraTreesClassifier

from sklearn.preprocessing import StandardScaler

In [2]:
df= pd.read_csv('TrainOnMe.csv')
df_val= pd.read_csv('EvaluateOnMe.csv')

In [3]:
pd.set_option('display.max_rows',1000)

In [4]:
rows=df[df.isna().any(axis=1)]
rows

Unnamed: 0                y        x1        x2  \
173                          173              NaN  -5.89826 -15.49745   
258     Þarf sás þér skal hvarfa              NaN       NaN       NaN   
259        þengill fyr kné lengi              NaN       NaN       NaN   
260      (svarar hógliga hverju)              NaN       NaN       NaN   
261      hugborð (konungr orði);              NaN       NaN       NaN   
262                fáir erum vér         né frýju       NaN       NaN   
263                       frændr   órum þó vændir       NaN       NaN   
264        (minnumk meir á annat              NaN       NaN       NaN   
265   mitt starf) konungdjarfir.              NaN       NaN       NaN   
446                          438           Atsuto -20.90675 -15.52179   
614                          606              Bob -21.60114 -15.41683   
704                          696              NaN -13.43997 -15.44248   
1000                         992              NaN -34.50822 -15.44613   

           x3        x4       x5                  x6        x7        x8  \
173   0.07850  15.76887  7.09385  Bayesian Inference  -9.45513 -41.74396   
258       NaN       NaN      NaN                 NaN       NaN       NaN   
259       NaN       NaN      NaN                 NaN       NaN       NaN   
260       NaN       NaN      NaN                 NaN       NaN       NaN   
261       NaN       NaN      NaN                 NaN       NaN       NaN   
262       NaN       NaN      NaN                 NaN       NaN       NaN   
263       NaN       NaN      NaN                 NaN       NaN       NaN   
264       NaN       NaN      NaN                 NaN       NaN       NaN   
265       NaN       NaN      NaN                 NaN       NaN       NaN   
446   0.58056  12.19680  3.43925                 NaN  -5.72169  -8.09088   
614   0.36192   4.86373 -1.77810                 NaN  -6.30774   1.74038   
704   0.17758  28.56231  4.05485  Bayesian Inference  -2.04917   3.64082   
1000  0.81278  19.22793  7.02529  Bayesian Inference -16.41150  45.73634   

            x9       x10       x11    x12  
173  -74.87425   5.62655 -20.14669  False  
258        NaN       NaN       NaN    NaN  
259        NaN       NaN       NaN    NaN  
260        NaN       NaN       NaN    NaN  
261        NaN       NaN       NaN    NaN  
262        NaN       NaN       NaN    NaN  
263        NaN       NaN       NaN    NaN  
264        NaN       NaN       NaN    NaN  
265        NaN       NaN       NaN    NaN  
446  -77.73056   8.28782 -20.17833  False  
614  -78.53296   7.62748 -20.04187  False  
704  -78.78604  10.53454 -20.07523  False  
1000 -80.30337  10.13587 -20.07997  False

In [5]:
df_zero_nan=df.drop([173,258,259,260,261,262,263,264,265,704,1000,742,830])

In [6]:
Grabbar = df_zero_nan['y'] #Grabbarna that we want to classify!
df_reduced =df_zero_nan.drop(columns=['y']) #reduced contains all the variables without the target variable.

In [7]:
# Make copy to avoid changing original data 

label_Y = Grabbar.copy()
label_encoder = LabelEncoder()
label_encoder.fit(['Atsuto','Bob','Jorg','Shoogee'])
list(label_encoder.classes_)
label_y = label_encoder.transform(label_Y)
label_y_df = pd.DataFrame(label_y, columns = ['Grabbar'])

In [29]:
df_first=df_reduced.drop(columns=['x6','x12','Unnamed: 0'])
df_val_last=df_val.drop(columns=['x6','x12','Unnamed: 0'])

In [10]:
classification_models = []
classification_models.append(('Random Forest', RandomForestClassifier(n_estimators=200, criterion="entropy",random_state=0)))#random_state=0
classification_models.append(('GaussianNaiveBayes',GaussianNB()))
classification_models.append(('SupportVectorMachineClassifier',SVC(kernel='rbf')))
classification_models.append(('KNN',KNeighborsClassifier(n_neighbors=15)))
classification_models.append(('XGboost',XGBClassifier()))
classification_models.append(('GradientBoostingClassifier',GradientBoostingClassifier()))
classification_models.append(('LogisticRegression',LogisticRegression(multi_class='multinomial')))
classification_models.append(('QuadraticDA',QuadraticDiscriminantAnalysis()))#priors=[0.1, 0.3, 0.2, 0.5]
classification_models.append(('LinearcDA',LinearDiscriminantAnalysis()))
classification_models.append(('DecisionTreeClassifier', DecisionTreeClassifier(criterion="entropy",random_state=0)))
classification_models.append(('BaggingClassifier', BaggingClassifier()))
classification_models.append(('MLPClassifier', MLPClassifier()))

In [18]:
def score(classification_models,X,Y):
    for i,v in classification_models:
        clf=v
        scores = cross_val_score(clf, X, Y, cv=5, verbose=1)
        print(i)
        print(scores)
        print("Score: %0.3f +- %0.3f" % (scores.mean(), scores.std()))
    return "done"

In [19]:
print(score(classification_models,df_first,label_y_df))

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
/Users/wojtasratusznik/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:531: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/Users/wojtasratusznik/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:531: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/Users/wojtasratusznik/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:531: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_trai

Random Forest
[0.71859296 0.71356784 0.69346734 0.73869347 0.74371859]
Score: 0.722 +- 0.018
GaussianNaiveBayes
[0.64824121 0.62311558 0.67336683 0.61809045 0.64824121]
Score: 0.642 +- 0.020
SupportVectorMachineClassifier
[0.54271357 0.57286432 0.50251256 0.51256281 0.53768844]
Score: 0.534 +- 0.025


/Users/wojtasratusznik/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:531: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/Users/wojtasratusznik/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:531: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed:    0.1s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
/Users/wojtasratusznik/opt/anaconda3/lib/python3.8/site-packages/xgboost/sklearn.py:888: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, 

KNN
[0.55778894 0.6281407  0.53768844 0.57286432 0.61809045]
Score: 0.583 +- 0.035
[16:46:00] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:1061: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[16:46:00] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:1061: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[16:46:00] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:1061: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[16:46:01] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:

[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed:    1.5s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
/Users/wojtasratusznik/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


XGboost
[0.72864322 0.73366834 0.67839196 0.69849246 0.72864322]
Score: 0.714 +- 0.022


/Users/wojtasratusznik/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
/Users/wojtasratusznik/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
/Users/wojtasratusznik/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
/Users/wojtasratusznik/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected.

GradientBoostingClassifier
[0.75376884 0.72361809 0.66834171 0.66331658 0.71356784]
Score: 0.705 +- 0.034


/Users/wojtasratusznik/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed:    0.2s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
/Users/wojtasratusznik/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
/Users/wojtasratusznik/opt/anaconda3/li

LogisticRegression
[0.54271357 0.51758794 0.5678392  0.59798995 0.53768844]
Score: 0.553 +- 0.028
QuadraticDA
[0.73869347 0.72361809 0.71859296 0.74371859 0.77889447]
Score: 0.741 +- 0.021
LinearcDA
[0.53266332 0.59798995 0.59798995 0.59296482 0.53266332]
Score: 0.571 +- 0.031
DecisionTreeClassifier
[0.65829146 0.66331658 0.65326633 0.64824121 0.68844221]
Score: 0.662 +- 0.014


/Users/wojtasratusznik/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
/Users/wojtasratusznik/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
/Users/wojtasratusznik/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
/Users/wojtasratusznik/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected.

BaggingClassifier
[0.69346734 0.69346734 0.65829146 0.70351759 0.69346734]
Score: 0.688 +- 0.016


/Users/wojtasratusznik/opt/anaconda3/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Users/wojtasratusznik/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
/Users/wojtasratusznik/opt/anaconda3/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Users/wojtasratusznik/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samp

MLPClassifier
[0.66834171 0.60301508 0.61306533 0.61306533 0.70854271]
Score: 0.641 +- 0.041
done


/Users/wojtasratusznik/opt/anaconda3/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed:    2.5s finished


In [39]:
scaler= StandardScaler()
X_train=scaler.fit_transform(df_first)
X_val=scaler.transform(df_val_last)

In [22]:
print(score(classification_models,X_train,label_y_df))

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
/Users/wojtasratusznik/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:531: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/Users/wojtasratusznik/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:531: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/Users/wojtasratusznik/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:531: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_trai

Random Forest
[0.71859296 0.71356784 0.69346734 0.73869347 0.74371859]
Score: 0.722 +- 0.018
GaussianNaiveBayes
[0.64824121 0.62311558 0.67336683 0.61809045 0.64824121]
Score: 0.642 +- 0.020
SupportVectorMachineClassifier
[0.71356784 0.68341709 0.71859296 0.70854271 0.72864322]
Score: 0.711 +- 0.015
KNN
[0.65326633 0.68844221 0.65326633 0.67839196 0.67839196]
Score: 0.670 +- 0.014
[16:47:57] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:1061: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[16:47:57] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:1061: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[16:47:58] WARNING: /Users/travis/build/dmlc/xgboo

[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed:    1.6s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
/Users/wojtasratusznik/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


XGboost
[0.72864322 0.73366834 0.67839196 0.69849246 0.72864322]
Score: 0.714 +- 0.022


/Users/wojtasratusznik/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
/Users/wojtasratusznik/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
/Users/wojtasratusznik/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
/Users/wojtasratusznik/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected.

GradientBoostingClassifier
[0.75376884 0.72361809 0.66331658 0.68844221 0.71356784]
Score: 0.709 +- 0.031
LogisticRegression
[0.54773869 0.57788945 0.59296482 0.59798995 0.53768844]
Score: 0.571 +- 0.024
QuadraticDA
[0.73869347 0.72361809 0.71859296 0.74371859 0.77889447]
Score: 0.741 +- 0.021
LinearcDA
[0.53266332 0.59798995 0.59798995 0.59296482 0.53266332]
Score: 0.571 +- 0.031
DecisionTreeClassifier
[0.65829146 0.66331658 0.65326633 0.64824121 0.68844221]
Score: 0.662 +- 0.014


/Users/wojtasratusznik/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
/Users/wojtasratusznik/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
/Users/wojtasratusznik/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
/Users/wojtasratusznik/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected.

BaggingClassifier
[0.71859296 0.66834171 0.66834171 0.71356784 0.69346734]
Score: 0.692 +- 0.021


/Users/wojtasratusznik/opt/anaconda3/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Users/wojtasratusznik/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
/Users/wojtasratusznik/opt/anaconda3/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Users/wojtasratusznik/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samp

MLPClassifier
[0.74371859 0.69849246 0.69849246 0.69849246 0.76884422]
Score: 0.722 +- 0.029
done


/Users/wojtasratusznik/opt/anaconda3/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed:    2.7s finished


In [36]:
estimators = [('rf', RandomForestClassifier(n_estimators=200,criterion="entropy", random_state=0)),('svr',SVC(kernel='rbf', decision_function_shape='ovr', break_ties=True, C=1.65, probability=True)),('quadraticDA',QuadraticDiscriminantAnalysis()),('MLPClassifier',MLPClassifier()),('xgboost',XGBClassifier(n_estimators=1000, verbosity=0))]#,('Knn',KNeighborsClassifier(n_neighbors=5, weights='distance')),("MLP",MLPClassifier(hidden_layer_sizes=(100, 100, 100, 100), activation="relu", solver="lbfgs")),('Logisticreg',LogisticRegression(max_iter=1000)),("ExtraTree",ExtraTreesClassifier(n_estimators=1000, max_depth=None))]
clf2 = StackingClassifier(estimators=estimators, final_estimator=LogisticRegression())
scores2 = cross_val_score(clf2, X_train, label_y_df, cv=5, verbose=1)
print("Score: %0.3f +- %0.3f" % (scores2.mean(), scores2.std()))
print(scores2)

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
/Users/wojtasratusznik/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
/Users/wojtasratusznik/opt/anaconda3/lib/python3.8/site-packages/sklearn/discriminant_analysis.py:715: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")
/Users/wojtasratusznik/opt/anaconda3/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Users/wojtasratusznik/opt/anaconda3/lib/python3.8/site-packages/xgboost/sklearn.py:888: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove

/Users/wojtasratusznik/opt/anaconda3/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Users/wojtasratusznik/opt/anaconda3/lib/python3.8/site-packages/xgboost/sklearn.py:888: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
/Users/wojtasratusznik/opt/anaconda3/lib/python3.8/site-packages/sklearn/discriminant_analysis.py:715: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")
/Users/wojtasratusznik/opt/anaconda3/lib/python3.8/site-packages/sklearn/discriminant_an

/Users/wojtasratusznik/opt/anaconda3/lib/python3.8/site-packages/sklearn/discriminant_analysis.py:715: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")
/Users/wojtasratusznik/opt/anaconda3/lib/python3.8/site-packages/sklearn/discriminant_analysis.py:715: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")
/Users/wojtasratusznik/opt/anaconda3/lib/python3.8/site-packages/sklearn/discriminant_analysis.py:715: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")
/Users/wojtasratusznik/opt/anaconda3/lib/python3.8/site-packages/sklearn/discriminant_analysis.py:715: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")
/Users/wojtasratusznik/opt/anaconda3/lib/python3.8/site-packages/sklearn/discriminant_analysis.py:715: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")
/Users/wojtasratusznik/opt/anaconda3/lib/python3.8/site-packages/sklearn/neural_netwo

Score: 0.756 +- 0.029
[0.77889447 0.71859296 0.72361809 0.76884422 0.78894472]


[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed:  1.1min finished


In [54]:
def evaluate(model,X,Y,X_val):
    clf=model
    clf.fit(X, Y)
    prediction=clf.predict(X_val)
    #Y_test_prediction=Y_test.to_numpy()
    #Y_test_prediction = np.concatenate( Y_test_prediction, axis=0)
    res2=label_encoder.inverse_transform(prediction)
    print(str(model))
    print('Shoogee')
    print(list(res2).count('Shoogee'))
    print('Atsuto')
    print(list(res2).count('Atsuto'))
    print('Bob')
    print(list(res2).count('Bob'))
    print('Jorg')
    print(list(res2).count('Jorg'))
    

In [55]:
evaluate(QuadraticDiscriminantAnalysis(),X_train,label_y_df,X_val)

QuadraticDiscriminantAnalysis()
Shoogee
1018
Atsuto
3260
Bob
3981
Jorg
1741


/Users/wojtasratusznik/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
/Users/wojtasratusznik/opt/anaconda3/lib/python3.8/site-packages/sklearn/discriminant_analysis.py:715: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")


In [56]:
evaluate(RandomForestClassifier(n_estimators=200, criterion="entropy",random_state=0),X_train,label_y_df,X_val)

<ipython-input-54-e79ecaf1b3cc>:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  clf.fit(X, Y)


RandomForestClassifier(criterion='entropy', n_estimators=200, random_state=0)
Shoogee
929
Atsuto
3613
Bob
3540
Jorg
1918


In [57]:
evaluate(SVC(kernel='rbf'),X_train,label_y_df,X_val)

SVC()
Shoogee
897
Atsuto
3978
Bob
3692
Jorg
1433


/Users/wojtasratusznik/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


In [58]:
evaluate(MLPClassifier(),X_train,label_y_df,X_val)

/Users/wojtasratusznik/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


MLPClassifier()
Shoogee
1004
Atsuto
3416
Bob
3676
Jorg
1904


/Users/wojtasratusznik/opt/anaconda3/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


In [59]:
evaluate(XGBClassifier(),X_train,label_y_df,X_val)

/Users/wojtasratusznik/opt/anaconda3/lib/python3.8/site-packages/xgboost/sklearn.py:888: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
/Users/wojtasratusznik/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints='',
              learning_rate=0.300000012, max_delta_step=0, max_depth=6,
              min_child_weight=1, missing=nan, monotone_constraints='()',
              n_estimators=100, n_jobs=8, num_parallel_tree=1,
              objective='multi:softprob', random_state=0, reg_alpha=0,
              reg_lambda=1, scale_pos_weight=None, subsample=1,
              tree_method='exact', validate_parameters=1, verbosity=None)
Shoogee
1013
Atsuto
3644
Bob
3372
Jorg
1971


In [60]:
evaluate(QuadraticDiscriminantAnalysis(),X_train,label_y_df,X_val)

QuadraticDiscriminantAnalysis()
Shoogee
1018
Atsuto
3260
Bob
3981
Jorg
1741


/Users/wojtasratusznik/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
/Users/wojtasratusznik/opt/anaconda3/lib/python3.8/site-packages/sklearn/discriminant_analysis.py:715: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")


In [61]:
evaluate(StackingClassifier(estimators=estimators, final_estimator=LogisticRegression()),X_train,label_y_df,X_val)

/Users/wojtasratusznik/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
/Users/wojtasratusznik/opt/anaconda3/lib/python3.8/site-packages/sklearn/discriminant_analysis.py:715: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")
/Users/wojtasratusznik/opt/anaconda3/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Users/wojtasratusznik/opt/anaconda3/lib/python3.8/site-packages/xgboost/sklearn.py:888: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when cons

StackingClassifier(estimators=[('rf',
                                RandomForestClassifier(criterion='entropy',
                                                       n_estimators=200,
                                                       random_state=0)),
                               ('svr',
                                SVC(C=1.65, break_ties=True, probability=True)),
                               ('quadraticDA', QuadraticDiscriminantAnalysis()),
                               ('MLPClassifier', MLPClassifier()),
                               ('xgboost',
                                XGBClassifier(base_score=None, booster=None,
                                              colsample_bylevel=None,
                                              colsample_bynode=None,
                                              co...
                                              interaction_constraints=None,
                                              learning_rate=None,
                   

In [62]:
evaluate(StackingClassifier(estimators=estimators, final_estimator=LogisticRegression()),X_train,label_y_df,X_val)

/Users/wojtasratusznik/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
/Users/wojtasratusznik/opt/anaconda3/lib/python3.8/site-packages/sklearn/discriminant_analysis.py:715: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")
/Users/wojtasratusznik/opt/anaconda3/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Users/wojtasratusznik/opt/anaconda3/lib/python3.8/site-packages/xgboost/sklearn.py:888: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when cons

StackingClassifier(estimators=[('rf',
                                RandomForestClassifier(criterion='entropy',
                                                       n_estimators=200,
                                                       random_state=0)),
                               ('svr',
                                SVC(C=1.65, break_ties=True, probability=True)),
                               ('quadraticDA', QuadraticDiscriminantAnalysis()),
                               ('MLPClassifier', MLPClassifier()),
                               ('xgboost',
                                XGBClassifier(base_score=None, booster=None,
                                              colsample_bylevel=None,
                                              colsample_bynode=None,
                                              co...
                                              interaction_constraints=None,
                                              learning_rate=None,
                   

In [63]:
evaluate(StackingClassifier(estimators=estimators, final_estimator=LogisticRegression()),X_train,label_y_df,X_val)

/Users/wojtasratusznik/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
/Users/wojtasratusznik/opt/anaconda3/lib/python3.8/site-packages/sklearn/discriminant_analysis.py:715: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")
/Users/wojtasratusznik/opt/anaconda3/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Users/wojtasratusznik/opt/anaconda3/lib/python3.8/site-packages/xgboost/sklearn.py:888: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when cons

StackingClassifier(estimators=[('rf',
                                RandomForestClassifier(criterion='entropy',
                                                       n_estimators=200,
                                                       random_state=0)),
                               ('svr',
                                SVC(C=1.65, break_ties=True, probability=True)),
                               ('quadraticDA', QuadraticDiscriminantAnalysis()),
                               ('MLPClassifier', MLPClassifier()),
                               ('xgboost',
                                XGBClassifier(base_score=None, booster=None,
                                              colsample_bylevel=None,
                                              colsample_bynode=None,
                                              co...
                                              interaction_constraints=None,
                                              learning_rate=None,
                   

In [64]:
evaluate(StackingClassifier(estimators=estimators, final_estimator=LogisticRegression()),X_train,label_y_df,X_val)

/Users/wojtasratusznik/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
/Users/wojtasratusznik/opt/anaconda3/lib/python3.8/site-packages/sklearn/discriminant_analysis.py:715: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")
/Users/wojtasratusznik/opt/anaconda3/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Users/wojtasratusznik/opt/anaconda3/lib/python3.8/site-packages/xgboost/sklearn.py:888: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when cons

StackingClassifier(estimators=[('rf',
                                RandomForestClassifier(criterion='entropy',
                                                       n_estimators=200,
                                                       random_state=0)),
                               ('svr',
                                SVC(C=1.65, break_ties=True, probability=True)),
                               ('quadraticDA', QuadraticDiscriminantAnalysis()),
                               ('MLPClassifier', MLPClassifier()),
                               ('xgboost',
                                XGBClassifier(base_score=None, booster=None,
                                              colsample_bylevel=None,
                                              colsample_bynode=None,
                                              co...
                                              interaction_constraints=None,
                                              learning_rate=None,
                   

In [87]:
def evaluate2(model,X,Y,X_val):
    clf=model
    clf.fit(X, Y)
    prediction=clf.predict(X_val)
    res2=label_encoder.inverse_transform(prediction)
    return res2

In [88]:
hello=evaluate2(StackingClassifier(estimators=estimators, final_estimator=LogisticRegression()),X_train,label_y_df,X_val)

/Users/wojtasratusznik/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
/Users/wojtasratusznik/opt/anaconda3/lib/python3.8/site-packages/sklearn/discriminant_analysis.py:715: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")
/Users/wojtasratusznik/opt/anaconda3/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Users/wojtasratusznik/opt/anaconda3/lib/python3.8/site-packages/xgboost/sklearn.py:888: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when cons

In [89]:
lista=list(hello)

In [90]:
lista.count('Bob')

3673

In [91]:
lista.count('Atsuto')

3442

In [92]:
lista.count('Shoogee')

1000

In [93]:
lista.count('Jorg')

1885

In [79]:
Grabbar.value_counts()

Bob        367
Atsuto     331
Jorg       209
Shoogee     88
Name: y, dtype: int64

In [94]:
lista

['Shoogee',
 'Shoogee',
 'Atsuto',
 'Atsuto',
 'Bob',
 'Bob',
 'Atsuto',
 'Jorg',
 'Atsuto',
 'Bob',
 'Jorg',
 'Shoogee',
 'Atsuto',
 'Atsuto',
 'Jorg',
 'Atsuto',
 'Atsuto',
 'Atsuto',
 'Bob',
 'Atsuto',
 'Bob',
 'Bob',
 'Bob',
 'Shoogee',
 'Bob',
 'Atsuto',
 'Bob',
 'Atsuto',
 'Bob',
 'Atsuto',
 'Jorg',
 'Atsuto',
 'Bob',
 'Jorg',
 'Atsuto',
 'Bob',
 'Bob',
 'Jorg',
 'Bob',
 'Bob',
 'Bob',
 'Atsuto',
 'Bob',
 'Atsuto',
 'Atsuto',
 'Atsuto',
 'Bob',
 'Atsuto',
 'Jorg',
 'Atsuto',
 'Jorg',
 'Atsuto',
 'Atsuto',
 'Bob',
 'Bob',
 'Shoogee',
 'Bob',
 'Shoogee',
 'Bob',
 'Atsuto',
 'Bob',
 'Jorg',
 'Atsuto',
 'Jorg',
 'Atsuto',
 'Atsuto',
 'Shoogee',
 'Jorg',
 'Atsuto',
 'Jorg',
 'Atsuto',
 'Bob',
 'Bob',
 'Shoogee',
 'Atsuto',
 'Atsuto',
 'Bob',
 'Bob',
 'Bob',
 'Jorg',
 'Atsuto',
 'Jorg',
 'Bob',
 'Bob',
 'Bob',
 'Atsuto',
 'Jorg',
 'Jorg',
 'Bob',
 'Jorg',
 'Jorg',
 'Atsuto',
 'Jorg',
 'Atsuto',
 'Bob',
 'Bob',
 'Atsuto',
 'Atsuto',
 'Atsuto',
 'Atsuto',
 'Shoogee',
 'Jorg',
 'Shoogee',

In [96]:
f=open('WojciechRatusznik_pred.txt','w')
for ele in lista:
    f.write(ele+'\n')

f.close()